name: Daily Report Emailer

on:
  schedule:
    # 14:20 UTC is exactly 7:50 PM IST
    - cron: '20 14 * * *'
  workflow_dispatch:

jobs:
  run-mailer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.9'

      - name: Install dependencies
        run: |
          pip install pymongo pytz

      - name: Run Email Script
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
        run: python daily_mailer.py
