name: Daily Report Emailer

on:
  schedule:
    # Runs at 14:30 UTC, which is 20:00 (8 PM) IST
    - cron: '55 5 * * *'
  workflow_dispatch: # Allows you to click a button to test it manually

jobs:
  run-mailer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pymongo pytz

      - name: Run Email Script
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
        run: python daily_mailer.py
