[general]
api_key = "AIzaSyBi26lZySMpOgwO4-9RuQ5GdkZFCy9vGRo"

[mongo]
username = "Akashdip_Saha"
password = "STIL@12345"
cluster_url = "cluster0.2zgbica.mongodb.net/"

[email]
sender_email = "akashdip.saha@jute-india.com"
sender_password = "zhfm gnoo dvtq xctm"
smtp_server = "smtp.gmail.com"
smtp_port = 587
